GET {{host}}/
Accept: application/json

###
POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    client.global.set("jwt", response.body.data);
%}

###

POST {{host}}/api/config/reload/all
Content-Type: application/json
Accept: application/json
Authorization: BEARER {{jwt}}